apiVersion: apps/v1
kind: Deployment
metadata:
  name: appecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appecommerce
  template:
    metadata:
      labels:
        app: appecommerce
    spec:
      volumes:
        - name: ecommercestorage
          persistentVolumeClaim:
            claimName: ecommercevolume
      containers:
        - name: appecommerce
          image: poornasrisrinu/appecommerce:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /app/data
              name: ecommercestorage
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appecommerce-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appecommerce
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: appecommerce-service
spec:
  selector:
    app: appecommerce
  ports:
    - name: http
      port: 5000
      nodePort: 30002
      targetPort: 5000
  type: LoadBalancer
